version: "3.9"
services: 
  php:
    image: jpswade/php7.4-fpm-alpine
    container_name: fpm-container
    volumes: 
      - ./backend:/app
      - ./log:/var/log/garm

  backend:
    tty: true
    image: nginx
    container_name: back-container
    restart: always
    working_dir: /app
    volumes:
      - ./docker/nginx/backend.conf:/etc/nginx/conf.d/backend.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend:/app
      - ./log/db:/var/log/garm
      - ./log/nginx/backend:/var/log/nginx
      - "./docker/createFile.sh:/docker-entrypoint-init-file.d/createFile.sh"    
    links:
      - php
      - database
  
  frontend:
    image: nginx
    container_name: frontend-container
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./docker/nginx/frontend.conf:/etc/nginx/conf.d/frontend.conf
      - ./frontend/dist:/app
      - ./log/nginx/frontend:/var/log/nginx

  database:
    image: mysql
    container_name: databasedemo-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
    environment:
      - "MYSQL_ROOT_PASSWORD=any_secret"
      - "MYSQL_USER=garm"
      - "MYSQL_PASSWORD=garm@2021"
    volumes:
      - garm-mysql-demo:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - "./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql"

      
volumes:
  garm-mysql-demo:
  fpm-data:
